=== darthrichlius/trenqr.com/product/view/def/dtd/dtd.pages_models.def.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT def.pages_models (model*) >
    <!ELEMENT model (model.id,model.files.css,model.files.js) >
        <!ATTLIST model id ID #REQUIRED>
        <!ELEMENT model.id EMPTY>
             <!ATTLIST model.id value CDATA #REQUIRED>
        <!ELEMENT model.files.css (std?,spec?)>
             <!ELEMENT std (media*,file*)>
				<!ELEMENT media EMPTY>
                    <!ATTLIST media name CDATA #REQUIRED>
                    <!ATTLIST media value CDATA #REQUIRED>
                <!ELEMENT file EMPTY>
                    <!ATTLIST file name CDATA #REQUIRED>
                    <!ATTLIST file value CDATA #REQUIRED>
            <!-- On requiert au moins un element 'brz' car si spec est defini,
                 il faut qu'il y ait au moins un element dedans. Sinon, autant ne pas le definir ! -->
            <!ELEMENT spec (brz+)>
            <!-- 'brz' signigie browser. Exemple : 'ie9'.
                'name' represente l'id du browser. On met 'name' pour permettre que plusieurs fichiers puissent etre définis pour un seul browser. 
                Voici une proposition de liste pour 'name' du brz
                * ie, ie6, ie7, ie8, ie9, ie10, iesupeg8, iesupeg9, ieinfeg9, ieinfeg8, ie<8                
                * chr
                * ope
                * saf
                * ffx
                 -->
                <!-- On utilise pas les vraix opérateurs > < car il faut les tradauire en &lt; ou &gt;. Pour l'instant on considère qu'il est plus intuitif d'utiliser les formes actuelles ! -->
                <!ELEMENT brz EMPTY>
                    <!ATTLIST brz name (ie | ie6 | ie7 | ie8 | ie9 | ie10 | ieinf8 | iesup8 | iesupeg8 | ieinfeg8 | ieinf9 | iesup9 | iesupeg9 | ieinfeg9 | ieinf10 | iesup10 | iesupeg10 | ieinfeg10 | chr | ope | saf | ffx) #REQUIRED>
                    <!ATTLIST brz value CDATA #REQUIRED>
        <!ELEMENT model.files.js (std?,spec?)>

=== darthrichlius/trenqr.com/product/view/def/model/def.pages_models.def.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE def.pages_models SYSTEM "../dtd/dtd.pages_models.def.dtd">

<def.pages_models>

    <model id="TMLNR_GTPG_WLC">
        <model.id value ="TMLNR_GTPG_WLC" />
        <model.files.css>
            <std>
                <!--<media name="media" value="screen and (min-width: 250px) and (max-width: 1400px);{wos/sysdir:stylesheet_dir_uri}/r/s/mdl15p.m.css?{wos/systx:now}" />-->
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/s/mdl15p.m.css?{wos/systx:now}" />
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/c.c/com.css" />
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/s/model21.css?{wos/systx:now}" />
                <!-- <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/s/model2.css?{wos/systx:now}" /> -->
                <!-- <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/d/profil-hdr-max.d.css?{wos/systx:now}" /> (01-07-15) -->
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/csam/pflbioplus_asdbox.csam.css?{wos/systx:now}" />
                <!-- <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/d/user_socprint.d.css?{wos/systx:now}" /> -->
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/d/aside_right_rest.d.css?{wos/systx:now}" />
                <!-- <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/d/hdr-with-co.d.css?{wos/systx:now}" /> -->
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/d/acc-header.d.css?{wos/systx:now}" />
                <!-- Account Feed n'est disponible que pour ce modoèle donc, déclaré comme vfiles de Model -->
                <!-- Cependant, il a été créé pour une dvt, il garde donc son extension *.d -->
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/d/accountFeed.d.css?{wos/systx:now}" />
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/csam/ua_event_corner.csam.css?{wos/systx:now}" />
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/d/legals.dvt.css?{wos/systx:now}" />
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/c.c/perfect-scrollbar-0.4.6.min.css" />
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/c.c/font-awesome.min.css?{wos/systx:now}" />
            </std>
        </model.files.css>
        <model.files.js>
        </model.files.js>
    </model>
	
    <model id="TMLNR_GTPG_RU">
        <model.id value ="TMLNR_GTPG_RU" />
        <model.files.css>
            <std>
                <!--<media name="media" value="screen and (min-width: 250px) and (max-width: 1400px);{wos/sysdir:stylesheet_dir_uri}/r/s/mdl15p.m.css?{wos/systx:now}" />-->
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/s/mdl15p.m.css?{wos/systx:now}" />
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/c.c/com.css" />
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/s/model21.css?{wos/systx:now}" />
                <!-- <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/s/model2.css?{wos/systx:now}" /> -->
                <!-- <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/d/profil-hdr-max.d.css?{wos/systx:now}" /> (01-07-15) -->
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/csam/pflbioplus_asdbox.csam.css?{wos/systx:now}" />
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/csam/asdapps.csam.css?{wos/systx:now}" />
                <!-- <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/d/user_socprint.d.css?{wos/systx:now}" /> -->
                
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/d/aside_right_rest.d.css?{wos/systx:now}" />
                <!--<file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/d/hdr-with-co.d.css?{wos/systx:now}" />-->
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/d/acc-header.d.css?{wos/systx:now}" />
                <!-- <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/c.c/badges.css?{wos/systx:now}" /> -->
                <!-- Account Feed n'est disponible que pour ce modèle donc, déclaré comme vfiles de Model -->
                <!-- Cependant, il a été créé pour une dvt, il garde donc son extension *.d -->
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/d/accountFeed.d.css?{wos/systx:now}" />
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/csam/ua_event_corner.csam.css?{wos/systx:now}" />
                <!--<file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/d/legals.dvt.css?{wos/systx:now}" />-->
                
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/s/tqs.m.css?{wos/systx:now}" />
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/c.c/crpr.min.css?{wos/systx:now}" />
                
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/c.c/perfect-scrollbar-0.4.6.min.css" />
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/c.c/jquery-ui.min.css" />
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/c.c/jquery.datetimepicker.css" />
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/c.c/font-awesome.min.css" />
            </std>
        </model.files.css>
        <model.files.js>
        </model.files.js>
    </model>
	
    <model id="TMLNR_GTPG_RO">
        <model.id value ="TMLNR_GTPG_RO" />
        <model.files.css>
            <std>
                <!--<media name="media" value="screen and (min-width: 250px) and (max-width: 1400px);{wos/sysdir:stylesheet_dir_uri}/r/s/mdl15p.m.css?{wos/systx:now}" />-->
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/s/mdl15p.m.css?{wos/systx:now}" />
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/c.c/com.css" />
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/s/model21.css?{wos/systx:now}" />
                <!-- <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/s/model2.css?{wos/systx:now}" /> -->
                <!-- <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/d/profil-hdr-max.d.css?{wos/systx:now}" /> (01-07-15) -->
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/csam/pflbioplus_asdbox.csam.css?{wos/systx:now}" />
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/csam/asdapps.csam.css?{wos/systx:now}" />
                <!-- <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/d/user_socprint.d.css?{wos/systx:now}" /> -->

                <!--<file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/d/hdr-with-co.d.css?{wos/systx:now}" />--> <!-- UnUSed -->
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/d/acc-header.d.css?{wos/systx:now}" />
                <!-- <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/c.c/badges.css?{wos/systx:now}" /> -->
                <!-- Account Feed n'est disponible que pour ce modèle donc, déclaré comme vfiles de Model -->
                <!-- Cependant, il a été créé pour une dvt, il garde donc son extension *.d -->
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/d/accountFeed.d.css?{wos/systx:now}" />
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/csam/ua_event_corner.csam.css?{wos/systx:now}" />
                <!--<file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/csam/tia.csam.css?{wos/systx:now}" />-->
                
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/s/tqs.m.css?{wos/systx:now}" />
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/c.c/crpr.min.css?{wos/systx:now}" />
                
                <!--<file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/d/legals.dvt.css?{wos/systx:now}" />--> <!-- UnUSed -->
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/c.c/perfect-scrollbar-0.4.6.min.css" />
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/c.c/jquery-ui.min.css" />
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/c.c/font-awesome.min.css?{wos/systx:now}" />
            </std>
        </model.files.css>
        <model.files.js>
        </model.files.js>
    </model>
	
    <model id="TRPG_GTPG_WLC">
        <model.id value ="TRPG_GTPG_WLC" />
        <model.files.css>
            <std>
                <!--<media name="media" value="screen and (min-width: 250px) and (max-width: 1400px);{wos/sysdir:stylesheet_dir_uri}/r/s/mdl15p.m.css?{wos/systx:now}" />-->
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/s/mdl15p.m.css?{wos/systx:now}" />
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/c.c/com.css" />
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/s/home_tr.m.css?{wos/systx:now}" />
                <!-- <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/c.c/flags-txt.css?{wos/systx:now}" /> -->
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/s/model21.css?{wos/systx:now}" />
                <!-- <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/s/model2.css?{wos/systx:now}" /> -->
                <!-- <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/d/user_socprint.d.css?{wos/systx:now}" /> -->
                <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/d/aside_right_rest.d.css?{wos/systx:now}" />
                <!-- <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/d/hdr-with-co.d.css?{wos/systx:now}" /> -->
                <!-- <file name="std" value="{wos/sysdir:stylesheet_dir_uri}/r/d/acc-header.d.css?{wos/systx:now}" /> -->
