=== darthrichlius/trenqr.com/product/view/def/dtd/dtd.pages.def.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT def.pages (page+) >
    <!ELEMENT page (creadate,last_mod_date,page.id,page.view.model,page.name,page.icon,page.title,page.keywords,page.description,page.author?,page.copyright?,page.meta.tq?,page.meta.og?,page.meta.twitter?,page.robots,page.pragma,page.cache_control,page.customs?) >
        <!ATTLIST page id ID #REQUIRED>
<!-- RecursFinder (l'algo qui recupèrre les données et les trie) ne nous permet pas d'avoir id. De plus, l'architecture du code ne nous le permet pas non plus  -->
<!-- Modifier l'archi serait plus compliqué et fastidieux que de modifier ce fichier  -->
        <!ELEMENT creadate EMPTY>
                <!ATTLIST creadate value CDATA #REQUIRED>
        <!ELEMENT last_mod_date EMPTY>
                <!ATTLIST last_mod_date value CDATA #REQUIRED>
        <!ELEMENT page.id EMPTY>
                <!ATTLIST page.id value CDATA #REQUIRED>
        <!-- On part du constat que plusieurs pages peuvent avoir un même modèle.
             Aussi, on crèe le concept de 'modèle'. Ce modèle s'affranchit du paradigme 'langue'. 
             La logique admet la succession suivante : page_id ->(1) modele ->(*) DVT(lang) ->BDD (pour les données en sortie)   
         -->
        <!ELEMENT page.view.model EMPTY>
            <!ATTLIST page.view.model value CDATA #REQUIRED>
        <!ELEMENT page.name (lang+)> 
            <!ELEMENT lang EMPTY>
                <!ATTLIST lang id CDATA #REQUIRED>
                <!ATTLIST lang value CDATA #REQUIRED>
        <!ELEMENT page.icon EMPTY>
                <!ATTLIST page.icon value CDATA #REQUIRED>
        
        <!ELEMENT page.title (lang+)>

        <!ELEMENT page.keywords (lang+)>

        <!ELEMENT page.description (lang+)>

        <!ELEMENT page.author EMPTY>
                <!ATTLIST page.author value CDATA #REQUIRED>
        <!ELEMENT page.copyright EMPTY>
                <!ATTLIST page.copyright value CDATA #REQUIRED>
		
        <!ELEMENT page.meta.tq (tq.meta*)>
            <!ELEMENT tq.meta EMPTY>
                <!ATTLIST tq.meta id CDATA #REQUIRED>
                <!ATTLIST tq.meta value CDATA #REQUIRED>

        <!ELEMENT page.meta.og (og.meta*)>
            <!ELEMENT og.meta EMPTY>
                <!ATTLIST og.meta id CDATA #REQUIRED>
                <!ATTLIST og.meta value CDATA #REQUIRED>

        <!ELEMENT page.meta.twitter (twt.meta*)>
            <!ELEMENT twt.meta EMPTY>
                <!ATTLIST twt.meta id CDATA #REQUIRED>
                <!ATTLIST twt.meta value CDATA #REQUIRED>
				

        <!ELEMENT page.robots EMPTY>
                <!ATTLIST page.robots value CDATA #REQUIRED>
        <!ELEMENT page.pragma EMPTY>
                <!ATTLIST page.pragma value CDATA #REQUIRED>
        <!ELEMENT page.cache_control EMPTY>
                <!ATTLIST page.cache_control value CDATA #REQUIRED>   

        <!-- 
            [DEPUIS 25-09-15] @author BOR 
                Permet de laisser la liberté à l'utilisateur de spécifier des balises.
        -->
        <!ELEMENT page.customs (page.custom*)>
            <!ELEMENT page.custom EMPTY>
                <!ATTLIST page.custom id CDATA #REQUIRED>
                <!ATTLIST page.custom value CDATA #REQUIRED>

=== darthrichlius/trenqr.com/__REPAIR_TQR_W/def.pages.def.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE def.pages SYSTEM "../dtd/dtd.pages.def.dtd">
<!--
[NOTE 29-09-15]
    Les textes sont fait pour mettre en avant les mots : "images"
-->

<def.pages>
    <page id="TMLNR_GTPG_WLC">
        <creadate value="2014-04-07" />
        <last_mod_date value="2015-09-2015" />
        <!-- **** -->
        <page.id value="TMLNR" />
        <page.view.model value="TMLNR_GTPG_WLC" />
        <page.name>
            <lang id="en" value="timeliner" />
            <lang id="fr" value="profil" />
        </page.name>
        <page.icon value="{wos/sysdir:img_dir_uri}/r/fav2.png" />
        <page.title>
            <lang id="en" value="{wos/datx:oufn} (@{wos/datx:oupsd}) - Trenqr • Photos, Tendances and Fun" />
            <lang id="fr" value="{wos/datx:oufn} (@{wos/datx:oupsd}) - Trenqr • Photos, Tendances et Fun" />
        </page.title> 
        <page.keywords>
            <lang id="en" value="{wos/datx:oufn}, {wos/datx:oupsd}, social network, images, pictures, images hosting, life images, buzzing pictures, gifs, animated gifs, visual storytelling, trends, friends community, fun community, cool community, trenqr" />
            <lang id="fr" value="{wos/datx:oufn}, {wos/datx:oupsd}, réseaux sociaux, communauté en ligne, plateforme communautaire, images, hébergement d'images, images du quotidien, images de ma vie, images qui buzz, gifs, gifs animés, tendances, ami, communauté cool, trenqr" />
        </page.keywords> 
        <page.description>
            <lang id="en" value="{wos/datx:oufn} (@{wos/datx:oupsd}) : {wos/datx:head_outesty} - Trenqr • Photos, Tendances and Fun" />
            <lang id="fr" value="{wos/datx:oufn} (@{wos/datx:oupsd}) : {wos/datx:head_outesty} - Trenqr • Photos, Tendances et Fun" />
        </page.description> 
<!--        <page.author value="DEUSLYNN ENTREPRISE" />
        <page.copyright value="DEUSLYNN ENTREPRISE, ALL RIGHTS RESERVED" />-->
        
        <!-- TQ META PROPERTIES --> 
        <page.meta.tq>
            <tq.meta id="pg" value="{wos/datx:pagid}" />
            <tq.meta id="ver" value="{wos/datx:pgakxver}" />
            <tq.meta id="ueid" value="{wos/datx:oueid}" />
            <tq.meta id="uppic" value="{wos/datx:ouppic}" />
            <tq.meta id="ufn" value="{wos/datx:oufn}" />
            <tq.meta id="upsd" value="{wos/datx:oupsd}" />
            <tq.meta id="uhref" value="{wos/datx:ouhref}" />
             <!-- UDL peut ne pas exister. Cette donner ne devrait pas être obligatoire. Elle ne sert en rien au traitement au niveau de FE -->
            <tq.meta id="udl" value="{wos/datx:oudl}" />
            <tq.meta id="ucity" value="{wos/datx:oucity_id}" />
            <tq.meta id="ucn" value="{wos/datx:oucn}" />
        </page.meta.tq>
        
        <!-- OG META PROPERTIES --> 
        <!-- 
            * [10-08-14] OpenGraph appartient à FB. Aussi, fournir des informations via ces balises est dansgereux. 
            * GooglePlus n'utilise que la balise titile. Ils utilisent aussi la balise twitter:title
            * On va donc ne transmettre que le titre de la page et le type.
        -->
        <!-- OG META PROPERTIES --> 
        <page.meta.og>
            <og.meta id="type" value="profile" />
            <og.meta id="title" value="{wos/datx:oufn} (@{wos/datx:oupsd}) on Trenqr" />
            <og.meta id="url" value="{wos/systx:prod_domain}/{wos/datx:oupsd}" />
            <og.meta id="image" value ="{wos/datx:ouppic}" />
            <og.meta id="image:width" value ="150px" />
        </page.meta.og>
        
        <!-- TWT META PROPERTIES --> 
        <page.meta.twitter>
            <twt.meta id="title" value="{wos/datx:oufn} (@{wos/datx:oupsd}) on Trenqr" />
            <twt.meta id="url" value="{wos/systx:prod_domain}/{wos/datx:oupsd}" />
        </page.meta.twitter>
        
        <!-- AUTRES METAS -->
        <page.robots value="index,follow,noimageindex,noarchive" />
        <page.pragma value="no-cache" />
        <page.cache_control value="no-cache" />
        <!-- [DEPUIS 25-09-15] @author BOR -->
        <page.customs>
             <page.custom id='0' value="&lt;link rel='canonical' href='{wos/systx:prod_domain}/{wos/datx:oupsd}' /&gt;" />
             <page.custom id='1' value="
                &lt;script&gt;
                (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

                ga('create', 'UA-68119085-1', 'auto');
                ga('send', 'pageview');
                &lt;/script&gt;" 
             />
             <page.custom id='2' value="&lt;meta name='viewport' content='width=device-width, initial-scale=1.0'&gt;" />
        </page.customs>
    </page>
	
    <page id="TMLNR_GTPG_RU">
        <creadate value="2014-04-07" />
        <last_mod_date value="2015-09-2015" />
        <!-- **** -->
        <page.id value="TMLNR" />
        <page.view.model value="TMLNR_GTPG_RU" />
        <page.name>
            <lang id="en" value="timeliner" />
            <lang id="fr" value="profil" />
        </page.name>
        <page.icon value="{wos/sysdir:img_dir_uri}/r/fav2.png" />
        <page.title>
            <lang id="en" value="{wos/datx:oufn} (@{wos/datx:oupsd}) - Trenqr • Photos, Tendances and Fun" />
            <lang id="fr" value="{wos/datx:oufn} (@{wos/datx:oupsd}) - Trenqr • Photos, Tendances et Fun" />
        </page.title> 
        <page.keywords>
            <lang id="en" value="{wos/datx:oufn}, {wos/datx:oupsd}, social network, images, pictures, images hosting, life images, buzzing pictures, gifs, animated gifs, visual storytelling, trends, friends community, fun community, cool community, trenqr" />
            <lang id="fr" value="{wos/datx:oufn}, {wos/datx:oupsd}, réseaux sociaux, communauté en ligne, plateforme communautaire, images, hébergement d'images, images du quotidien, images de ma vie, images qui buzz, gifs, gifs animés, tendances, ami, communauté cool, trenqr" />
        </page.keywords> 
        <page.description>
            <lang id="en" value="{wos/datx:oufn} (@{wos/datx:oupsd}) : {wos/datx:head_outesty} - Trenqr • Photos, Tendances and Fun" />
            <lang id="fr" value="{wos/datx:oufn} (@{wos/datx:oupsd}) : {wos/datx:head_outesty} - Trenqr • Photos, Tendances et Fun" />
        </page.description> 
<!--        <page.author value="DEUSLYNN ENTREPRISE" />
        <page.copyright value="DEUSLYNN ENTREPRISE, ALL RIGHTS RESERVED" />-->
        
        <!-- TQ META PROPERTIES --> 
        <page.meta.tq>
            <tq.meta id="pg" value="{wos/datx:pagid}" />
            <tq.meta id="ver" value="{wos/datx:pgakxver}" />
            <tq.meta id="ueid" value="{wos/datx:oueid}" />
            <tq.meta id="uppic" value="{wos/datx:ouppic}" />
            <tq.meta id="ufn" value="{wos/datx:oufn}" />
            <tq.meta id="upsd" value="{wos/datx:oupsd}" />
            <tq.meta id="uhref" value="{wos/datx:ouhref}" />
             <!-- UDL peut ne pas exister. Cette donner ne devrait pas être obligatoire. Elle ne sert en rien au traitement au niveau de FE -->
            <tq.meta id="udl" value="{wos/datx:oudl}" />
            <tq.meta id="ucity" value="{wos/datx:oucity_id}" />
            <tq.meta id="ucn" value="{wos/datx:oucn}" />
        </page.meta.tq>
        
       <!-- OG META PROPERTIES --> 
        <page.meta.og>
            <og.meta id="type" value="profile" />
            <og.meta id="title" value="{wos/datx:oufn} (@{wos/datx:oupsd}) on Trenqr" />
            <og.meta id="url" value="{wos/systx:prod_domain}/{wos/datx:oupsd}" />
            <og.meta id="image" value ="{wos/datx:ouppic}" />
            <og.meta id="image:width" value ="150px" />
        </page.meta.og>
        
        <!-- TWT META PROPERTIES --> 
        <page.meta.twitter>
            <twt.meta id="title" value="{wos/datx:oufn} (@{wos/datx:oupsd}) on Trenqr" />
            <twt.meta id="url" value="{wos/systx:prod_domain}/{wos/datx:oupsd}" />
        </page.meta.twitter>
        
        <!-- AUTRES METAS -->
        <page.robots value="noindex,nofollow,noimageindex,noarchive" />
        <page.pragma value="no-cache" />
        <page.cache_control value="no-cache" />
        <!-- [DEPUIS 25-09-15] @author BOR -->
        <page.customs>
             <page.custom id='0' value="&lt;link rel='canonical' href='{wos/systx:prod_domain}/{wos/datx:oupsd}' /&gt;" />
        </page.customs>
    </page>
	
    <page id="TMLNR_GTPG_RO">
        <creadate value="2014-04-08" />
        <last_mod_date value="2015-09-2015" />
        <!-- **** -->
        <page.id value="TMLNR" />
        <page.view.model value="TMLNR_GTPG_RO" />
        <page.name>
            <lang id="en" value="timeliner" />
            <lang id="fr" value="profil" />
        </page.name>
        <page.icon value="{wos/sysdir:img_dir_uri}/r/fav2.png" />
        <page.title>
            <lang id="en" value="{wos/datx:oufn} (@{wos/datx:oupsd}) - Trenqr • Photos, Tendances and Fun" />
            <lang id="fr" value="{wos/datx:oufn} (@{wos/datx:oupsd}) - Trenqr • Photos, Tendances et Fun" />
        </page.title> 
        <page.keywords>
            <lang id="en" value="{wos/datx:oufn}, {wos/datx:oupsd}, social network, images, pictures, images hosting, life images, buzzing pictures, gifs, animated gifs, visual storytelling, trends, friends community, fun community, cool community, trenqr" />
            <lang id="fr" value="{wos/datx:oufn}, {wos/datx:oupsd}, réseaux sociaux, communauté en ligne, plateforme communautaire, images, hébergement d'images, images du quotidien, images de ma vie, images qui buzz, gifs, gifs animés, tendances, ami, communauté cool, trenqr" />
        </page.keywords> 
        <page.description>
