=== darthrichlius/trenqr.com/product/data/dtd/dtd.email_models.def.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT email_models (emodel*) >
    <!ELEMENT emodel (emodel.id,emodel.type,emodel.object,emodel.body) >
        <!ATTLIST emodel id ID #REQUIRED>
        <!ELEMENT emodel.id EMPTY>
            <!ATTLIST emodel.id value CDATA #REQUIRED>
        <!ELEMENT emodel.type EMPTY>
            <!ATTLIST emodel.type value CDATA #REQUIRED>
        <!ELEMENT emodel.object EMPTY>
            <!ATTLIST emodel.object value CDATA #REQUIRED>
        <!ELEMENT emodel.body EMPTY>
            <!ATTLIST emodel.body value CDATA #REQUIRED>

=== darthrichlius/trenqr.com/product/data/email/fr/def.email_models.def.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE email_models SYSTEM "../../dtd/dtd.email_models.def.dtd">

<email_models>
    <emodel id="emdl_sample">
        <emodel.id value="emdl_sample" />
        <emodel.type value="text/html" />
        <emodel.object value="Un sample pour le developpement, les tests ou debug." />
        <emodel.body 
            value="
                &lt;p&gt;Bonjour,&lt;/p&gt;
                &lt;p&gt;
                    Mon nom est Wall.E ! Je suis là pour t'aider dans tes tâches ô combien difficiles cher maitre développeur.&lt;br/&gt;
                    Tu peux me contacter via ce &lt;a href=''&gt;lien fictif&lt;/a&gt; qui ne te menera nulle part. &lt;br/&gt;
                    Tu peux aussi t'entrainer à remplacer ce %{marqueur}%.
                &lt;/p&gt;
                &lt;p&gt;Souviens toi que pour les emaux de type html, la technique c'est de saisir le texte avec les '&lt;' '&gt;' puis de les remplacer avec un Ctrl+H ciblé.&lt;/p&gt;
                &lt;p&gt;
                    Sinon, tu peux toujours corriger l'orthographe de ce texte si tu constates les erreurs commises. BON CHANCE !
                &lt;/p&gt;
                &lt;p&gt;Cordiallement,&lt;/p&gt;
                &lt;p&gt;WALL.E et E.V.E&lt;/p&gt;
            " />
    </emodel>
    <emodel id="emdl_errlgn1">
        <emodel.id value="emdl_errlgn1" />
        <emodel.type value="text/html" />
        <emodel.object value="Rapport d'erreur critique." />
        <emodel.body 
            value="
                &lt;!DOCTYPE html&gt;
                &lt;html&gt;
                    &lt;head&gt;
                        
                    &lt;/head&gt;
                    &lt;body&gt;
                &lt;div style='font-family: Calibri, Arial, sans-serif'&gt;
                    &lt;p style='font-style: italic;'&gt;Hey !&lt;/p&gt;
                    &lt;p&gt;
                        Cet email est envoyé à la suite du déclenchement d'une erreur detectée depuis le produit &lt;span style='color: rgb(28,140,255); font-weight: bold;'&gt;Trenqr&lt;/span&gt;.&lt;br/&gt;
                        Ci-dessous les données relatives à l'erreur : 
                    &lt;/p&gt;
                    &lt;h2 style='color: #555;'&gt;RAPPORT DÉTAILLÉ :&lt;/h2&gt;
                    &lt;table style='border: 1px solid #000; border-collapse: collapse;'&gt;
                        &lt;tr&gt;
                            &lt;th style='border-bottom: 1px solid #000; border-right: 1px solid #000; font-size: 20px; font-weight: bold; background-color: #ccc; text-align: center;'&gt;PROPRIÉTÉS&lt;/th&gt;
                            &lt;th style='border-bottom: 1px solid #000; border-right: 1px solid #000; font-size: 20px; font-weight: bold; background-color: #ccc; text-align: center;'&gt;VALEURS&lt;/th&gt;
                        &lt;/tr&gt;
                        &lt;tr&gt;
                            &lt;td style='font-size: 16px; font-weight: bold;'&gt;ERROR CODE : &lt;/td&gt;
                            &lt;td style='color: #f00'&gt;%{error_code}%&lt;/td&gt;
                        &lt;/tr&gt;
                        &lt;tr&gt;
                            &lt;td style='font-size: 16px; font-weight: bold;'&gt;ERROR MESSAGE : &lt;/td&gt;
                            &lt;td style='color: #f00'&gt;%{error_message}%&lt;/td&gt;
                        &lt;/tr&gt;
                        &lt;tr style='color: #28b957; font-weight: bold; text-align: center;'&gt;
                            &lt;td&gt;WHO STUFF&lt;/td&gt;
                            &lt;td&gt;&lt;/td&gt;
                        &lt;/tr&gt;
                        &lt;tr&gt;
                            &lt;td style='font-size: 16px; font-weight: bold;'&gt;SESSION_ID: &lt;/td&gt;
                            &lt;td&gt;%{ssid}%&lt;/td&gt;
                        &lt;/tr&gt;
                        &lt;tr&gt;
                            &lt;td style='font-size: 16px; font-weight: bold;'&gt;USER EID : &lt;/td&gt;
                            &lt;td&gt;%{error_user_ueid}%&lt;/td&gt;
                        &lt;/tr&gt;
                        &lt;tr&gt;
                            &lt;td style='font-size: 16px; font-weight: bold;'&gt;USER PSEUDO : &lt;/td&gt;
                            &lt;td&gt;%{error_user_pseudo}%&lt;/td&gt;
                        &lt;/tr&gt;
                        &lt;tr&gt;
                            &lt;td style='font-size: 16px; font-weight: bold;'&gt;ERROR LOCIP ADDR : &lt;/td&gt;
                            &lt;td&gt;%{error_locip}%&lt;/td&gt;
                        &lt;/tr&gt;
                        &lt;tr style='color: #28b957; font-weight: bold; text-align: center;'&gt;
                            &lt;td&gt;WHERE STUFF&lt;/td&gt;
                            &lt;td&gt;&lt;/td&gt;
                        &lt;/tr&gt;
                        &lt;tr&gt;
                            &lt;td style='font-size: 16px; font-weight: bold;'&gt;ERROR SRVIP: &lt;/td&gt;
                            &lt;td&gt;%{error_srvip}%&lt;/td&gt;
                        &lt;/tr&gt;
                        &lt;tr&gt;
                            &lt;td style='font-size: 16px; font-weight: bold;'&gt;ERROR SRVNAME : &lt;/td&gt;
                            &lt;td&gt;%{error_srvname}%&lt;/td&gt;
                        &lt;/tr&gt;
                        &lt;tr&gt;
                            &lt;td style='font-size: 16px; font-weight: bold;'&gt;ERROR FILE : &lt;/td&gt;
                            &lt;td&gt;%{error_file}%&lt;/td&gt;
                        &lt;/tr&gt;
                        &lt;tr&gt;
                            &lt;td style='font-size: 16px; font-weight: bold;'&gt;ERROR CLASS : &lt;/td&gt;
                            &lt;td&gt;%{error_class}%&lt;/td&gt;
                        &lt;/tr&gt;
                        &lt;tr&gt;
                            &lt;td style='font-size: 16px; font-weight: bold;'&gt;ERROR FUNCTION : &lt;/td&gt;
                            &lt;td&gt;%{error_function}%&lt;/td&gt;
                        &lt;/tr&gt;
                        &lt;tr&gt;
                            &lt;td style='font-size: 16px; font-weight: bold;'&gt;ERROR LINE : &lt;/td&gt;
                            &lt;td&gt;%{error_line}%&lt;/td&gt;
                        &lt;/tr&gt;
                        &lt;tr style='color: #28b957; font-weight: bold; text-align: center;'&gt;
                            &lt;td&gt;HOW STUFF&lt;/td&gt;
                            &lt;td&gt;&lt;/td&gt;
                        &lt;/tr&gt;
                        &lt;tr&gt;
                            &lt;td style='font-size: 16px; font-weight: bold;' valign='top'&gt;ERROR REFERER : &lt;/td&gt;
                            &lt;td&gt;%{error_referer}%&lt;/td&gt;
                        &lt;/tr&gt;
                        &lt;tr&gt;
                            &lt;td style='font-size: 16px; font-weight: bold;' valign='top'&gt;ERROR URI : &lt;/td&gt;
                            &lt;td&gt;%{error_uri}%&lt;/td&gt;
                        &lt;/tr&gt;
                        &lt;tr&gt;
                            &lt;td style='font-size: 16px; font-weight: bold;' valign='top'&gt;ERROR USER AGENT : &lt;/td&gt;
                            &lt;td&gt;%{error_user_agent}%&lt;/td&gt;
                        &lt;/tr&gt;
                        &lt;tr&gt;
                            &lt;td style='font-size: 16px; font-weight: bold;' valign='top'&gt;ERROR TRACE : &lt;/td&gt;
                            &lt;td style='width: 500px;'&gt;%{debug_print_trace}%&lt;/td&gt;
                        &lt;/tr&gt;
                        &lt;tr style='color: #28b957; font-weight: bold; text-align: center;'&gt;
                            &lt;td&gt;WHEN STUFF&lt;/td&gt;
                            &lt;td&gt;&lt;/td&gt;
                        &lt;/tr&gt;
                        &lt;tr&gt;
                            &lt;td style='font-size: 16px; font-weight: bold;'&gt;ERROR DATE : &lt;/td&gt;
                            &lt;td&gt;%{error_date_tstamp}% (%{error_datetime}%)&lt;/td&gt;
                        &lt;/tr&gt;
                        &lt;tr style='color: rgb(230,10,10); font-weight: bold; text-align: center;'&gt;
                            &lt;td&gt;LOGGED STUFF&lt;/td&gt;
                            &lt;td&gt;&lt;/td&gt;
                        &lt;/tr&gt;
                        &lt;tr&gt;
                            &lt;td style='font-size: 16px; font-weight: bold;'&gt;ERROR LOG EID : &lt;/td&gt;
                            &lt;td&gt;%{error_log_eid}%&lt;/td&gt;
                        &lt;/tr&gt;
                    &lt;/table&gt;
                &lt;/div&gt;
                    &lt;/body&gt;
                &lt;/html&gt;
            " />
    </emodel>
	<emodel id="emdl_newaccn1">
        <emodel.id value="emdl_newaccn1" />
        <emodel.type value="text/html" />
        <emodel.object value="Bienvenue sur Trenqr !" />
        <emodel.body 
            value="
                &lt;div id='new-acc-panel-mx' style='
                    border: 1px solid #ccc; 
                    border-radius: 2px; width: 700px; 
                    height: 100%; 
                    margin: 20px auto; 
                    background-color: #003A78; 
                    position: relative; 
                    overflow: auto;
                    color: #000;'
                &gt;
                &lt;div id='n-a-pan-left' style='width: 150px; height: 100%; background-color: #003A78; float: left;'&gt;
                    &lt;div id='n-a-pan-l-logo' style='margin: 20px 0px 0px 0px;'&gt;
                        &lt;div id='' style='text-align: center;'&gt;
                            &lt;a href='%{trenqr_http_root}%'&gt;&lt;img height='50px' src='%{trenqr_prod_img_root}%/r/logo_tqr_beta.png' /&gt;&lt;/a&gt;
                        &lt;/div&gt;
                        &lt;div id='n-a-p-logo' style='
